apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim3
  namespace: kubeflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi