apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pipeline2
  namespace: kubeflow
spec:
  storageClassName: nfs-client 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
