apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-mnist-webui 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: kf-mnist-webui
    spec:
      containers:
      - name: kf-mnist-webui
        image: brightfly/kfserving-mnist-web-ui:latest
        ports:
        - containerPort: 5000 
