kind: Service
apiVersion: v1
metadata:
  name: kf-mnist-webui-service
spec:
  selector:
    deployment: kf-mnist-webui
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 32000
    port: 5000
    targetPort: 5000
